blank_issues_enabled: false
contact_links:
  - name: Contributing guide
    url: https://github.com/paulocanedo/sc2-replay-utils/blob/master/.github/CONTRIBUTING.md
    about: Read this before opening a pull request.
